name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

  deliver:

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
          uses: actions/checkout@v4

      - name: Simulando Continuous delivery
          uses: actions/upload-artifact@v4
          with:
            name: projetozip.zip
            path:
             '**.html'
             README.md

   deploy:

      runs-on: ubuntu-latest
      needs: deliver
      
    steps:
        - uses: actions/downsload-artifact@v4
          with:
            name: projetozip.zip
        - name: Display structure of download files
          run: ls -R
